# Assignment 1

- Write a function so that the columns of the output matrix are powers of the input vector. The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

- HINT: Such a matrix with a geometric progression in each row is named for Alexandre-Theophile Vandermonde.

In [12]:
import numpy as np

def ATV_matrix(vector, cols, inc):
    vector= vector.split(',')
    vector= np.array([int(i) for i in vector])
    if inc.upper()=='N':
        atv= np.array([i**(cols-col-1) for i in vector for col in range(cols)]).reshape(vector.size, cols)
    else:
        atv= np.array([i**col for i in vector for col in range(cols)]).reshape(vector.size, cols)
    print(atv)
    
vector= input('Enter the input vector (num1, num2, num3...): ')
cols= int(input('Enter the number of columns: '))
inc= str(input('Should the powers increase? Y/N: '))

ATV_matrix(vector, cols, inc)

Enter the input vector (num1, num2, num3...):  1,2,3,4,5
Enter the number of columns:  7
Should the powers increase? Y/N:  Y


[[    1     1     1     1     1     1     1]
 [    1     2     4     8    16    32    64]
 [    1     3     9    27    81   243   729]
 [    1     4    16    64   256  1024  4096]
 [    1     5    25   125   625  3125 15625]]


# Assignment 2
- Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given sequence is defined as follows:
    - The moving average sequence has n-k+1 elements as shown below.
    - The moving averages with k=4 of a ten-value sequence (n=10) is shown below
        - i 1 2 3 4 5 6 7 8 9 10
        - ===== == == == == == == == == == ==
        - Input 10 20 30 40 50 60 70 80 90 100
        - y1 25 = (10+20+30+40)/4
        - y2 35 = (20+30+40+50)/4
        - y3 45 = (30+40+50+60)/4
        - y4 55 = (40+50+60+70)/4
        - y5 65 = (50+60+70+80)/4
        - y6 75 = (60+70+80+90)/4
        - y7 85 = (70+80+90+100)/4
    - Thus, the moving average sequence has n-k+1=10-4+1=7 values
    

- Question: Write a function to find moving average in an array over a window: Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [24]:
def moving_avg(vector, window):
    vector= vector.split(',')
    vector= np.array([int(i) for i in vector])
    vec_sum= np.cumsum(vector)    
    vec_sum[window:]= vec_sum[window:]-vec_sum[:-window]   
    print(np.round_(vec_sum/window, decimals = 2))
    
vector= input('Enter the input vector (num1, num2, num3...): ')
window= int(input('Enter the window size: '))

moving_avg(vector, window)

Enter the input vector (num1, num2, num3...):  3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150
Enter the window size:  3


[  1.     2.67   5.     4.67   5.67   6.67   9.67  28.67  49.33  72.67
  84.    93.33 116.33]
